version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket serverless-cicd-helloworld --output-template-file outputTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml