version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --output-template-file outputTemplate.yaml --s3-bucket serverless-cicd-helloworld
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml